### ISSUE TITLE
Remove vendor tag

### ISSUE THREAD

**Issue by grylem** [Sound-Linux-More/opuscomment#1]
Здравствуйте,
можете добавить возможность удаления vendor tag как у  metaflac --remove-all?
Спасибо.

**Comment by zvezdochiot** [comment]
Hi @grylem .

Возникла заминка. Как такового vendor tag в OPUS нет. Это просто "безымянная" (в отличии от остальных) корневая запись к блоке meta. Как получить к ней доступ - я не понял. Не могу помочь.

**Comment by grylem** [comment]
Hi @zvezdochiot
а для flac? Ведь opusscomment поддерживает и flac.

**Comment by zvezdochiot** [comment]
Hi @grylem .

Для `flac` есть `metaflac`.

**Comment by grylem** [comment]
Hi @zvezdochiot 
вы правы, но в этом случае opuscomment записывает свой vendor tag.

Есть еще вопрос по вашей программе opuspictotag: не могли бы вы добавить возможность добавления коментария к обложке?

**Comment by zvezdochiot** [comment]
Hi @grylem .

Какой "свой"? Нету вроде никакого "своего". Или я что то забыл?

Можете добавлять любые (ЛЮБЫЕ!) теги. Но какой из них относится к обложке я не помню.

**Comment by zvezdochiot** [comment]
Hi @grylem .

Вспомнил в чём дело. Это "заглушка" от бага. В пределах `opuscomment` без неё никак нельзя. Ваш вопрос не может быть решён в пределах `opuscomment`.

**Comment by grylem** [comment]
Hi @zvezdochiot 
ваша программа opuspictotag грубо говоря конвертирует обложку в base64 и комментарий должен быть встроен именно туда, так как это делает shell script из пакета opuscomment. Если использовать opuspictotag в в связке с opuscomment то добавить комментарий к оюложке не получится т.к. у opuscomment нет такого функционала.
Т. е. приблизительно это должно выглядеть так:
opuspictotag текст image.png

**Comment by zvezdochiot** [comment]
Hi @grylem .

Покажите как это делает `opusenc` (или что то ещё). А то я вас понять не могу.

**Comment by grylem** [comment]
Hi @zvezdochiot 
opusmbptag.sh -d zvezdochiot cover.png | opuscomment -w file.opus
exiftool file.opus
....
Picture Type                    : Front Cover
Picture MIME Type               : image/png
Picture Description             : zvezdochiot
....

**Comment by zvezdochiot** [comment]
Hi @grylem .

Так что не нравится? Извлечь изображение вы всегда с помощью `ffmpeg` можете. Или даже декодировать `base64`. Какую "задачу" вы решить на самом деле не можете?

PS: Или вы не можете объединить изображение с остальными тегами?
```sh
opuscomment file.opus > file.opustags
opusmbptag.sh -d "You picture comment" cover.png >> file.opustags
cat file.opustags | opuscomment -w file.opus
```
См. также https://github.com/Sound-Linux-More/opuscomment/blob/master/doc/samples/sample_audiobook.opustags

**Comment by grylem** [comment]
Возможно вы неверно меня поняли. Вы написали программу opuspictotag являющуяся аналогом скрипта
opusmbptag.sh. И именно в вашей программе отстуствует возможность добавления комментариев к обложке и не только это. Не могли бы вы внести изменения в вашу программу чтобы она служила полной заменой opusmbptag.sh?

**Comment by zvezdochiot** [comment]
Hi @grylem .

Нет. [Та библиотека](https://github.com/Sound-Linux-More/opustags) кривая. Прежде чем добавлять какие то "причуды", надо исправить саму библиотеку. Но я давно уже её забросил за ненадобностью. (для моих целей она оказалась бесполезной, да и кривая ещё).

**Comment by zvezdochiot** [comment]
Hi @grylem .

Что то я намутил. Посмотри последний коммит: https://github.com/Sound-Linux-More/opuscomment/commit/f5188577965040f81f5e852360518aab1b78e77c
