### ISSUE TITLE
opuspic2tag

### ISSUE THREAD

**Issue by grylem** [Sound-Linux-More/opuscomment#2]
Привет.
Можете добавить возможность чтения из stdin?
Планируете ли добавить чтение комментария из файла как -D у скрипта opusmbptag.sh и -m mime?
opuspic2tag cover.jpg выводит в stdout без новой строки в конце в отличие от opusmbptag.sh и остальных программ, можете поправить?

**Comment by zvezdochiot** [comment]
@grylem say:
>Можете добавить возможность чтения из stdin?

Нет. Автодетектирование mime убивает однопроходность.

@grylem say:
>Планируете ли добавить чтение комментария из файла как -D у скрипта opusmbptag.sh и -m mime?

Нет. Это какой то оверхэд. И в отличии от скрипта, использующего команду `file`, автодетектирование mime не требует коррекции. Наоборот.

@grylem say:
>opuspic2tag cover.jpg выводит в stdout без новой строки в конце в отличие от opusmbptag.sh и остальных программ,

А вот это можно поправить.

**Comment by grylem** [comment]
Hi @zvezdochiot
может передумаете? Чтение из stdin очень удобно в связке с ImageMagick и подобными программами, а взможность добавления параметров mime-type и WIDTHxHEIGHTxDEPTH/COLORS предусмотрена спецификациями opus, flac и ogg.

Чтение комментария к обложке из файла просто удобно когда использутся несколько строк, а не одна.

Спасибо.

**Comment by zvezdochiot** [comment]
@grylem say:
>может передумаете?

Да хоть обпередумывайся. Magic-детект срубает однопроходность на корню. Плюс беда с обрубанием файла на неизвестном месте в stdin. Ну его к чорту.
